### ISSUE TITLE
Why The Cargo Workspace?

### ISSUE THREAD

**Issue by sno2** [keiya01/og_image_writer#1]
Cargo crates support having a standalone `examples` folder within them which can be run via `cargo run --example foo`.  In that case, it would run `examples/foo.rs` or `examples/foo/mod.rs`.  You would still be able to use your `og_image_writer` main crate just by doing `use og_image_writer` so no code changes required as I see it.

**Comment by keiya01** [comment]
The reason why I'm using the cargo workspace is because I have the plan to add related lib in the future.

**Comment by sno2** [comment]
> The reason why I'm using the cargo workspace is because I have the plan to add related lib in the future.

Ah, makes sense.
